---
- name: Docker | EE | YUM | Oracle Linux | Disable UEK R3
  yum_repository:
    name: ol7_UEKR3
    description: Latest Unbreakable Enterprise Kernel Release 3 for Oracle Linux $releasever ($basearch)
    baseurl: "http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/$basearch/"
    enabled: 0
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  when: ansible_distribution_major_version == "7"

- name: Docker | EE | YUM | Oracle Linux | Enable UEK R4
  yum_repository:
    name: ol7_UEKR4
    description: Latest Unbreakable Enterprise Kernel Release 4 for Oracle Linux $releasever ($basearch)
    baseurl: "http://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/$basearch/"
    enabled: 1
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  when: ansible_distribution_major_version == "7"
