---
dist: trusty
sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

env:
  global:
    - ROLE_NAME: docker
  matrix:
    - MOLECULE_DISTRO: centos:7
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: fedora:27
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: fedora:28
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /usr/sbin/init
    - MOLECULE_DISTRO: ubuntu-upstart:trusty
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: ubuntu:xenial
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: ubuntu:bionic
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /lib/systemd/systemd
    - MOLECULE_DISTRO: debian:wheezy
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: debian:jessie
      MOLECULE_COMMAND: /sbin/init
    - MOLECULE_DISTRO: debian:stretch
      MOLECULE_SERVICE_MANAGER: systemd
      MOLECULE_COMMAND: /lib/systemd/systemd

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-role-$ROLE_NAME avinetworks.$ROLE_NAME
  - cd avinetworks.$ROLE_NAME

script:
  - molecule --debug test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
