---
- name: YUM | Disable UEK R3 for Oracle Linux
  yum_repository:
    name: ol7_UEKR3
    description: Latest Unbreakable Enterprise Kernel Release 3 for Oracle Linux $releasever ($basearch)
    baseurl: "http://yum.oracle.com/repo/OracleLinux/OL7/UEKR3/$basearch/"
    enabled: 0
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "7"

- name: YUM | Enable UEK R4 for Oracle Linux
  yum_repository:
    name: ol7_UEKR4
    description: Latest Unbreakable Enterprise Kernel Release 4 for Oracle Linux $releasever ($basearch)
    baseurl: "http://yum.oracle.com/repo/OracleLinux/OL7/UEKR4/$basearch/"
    enabled: 1
    gpgcheck: 1
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle
  when: ansible_distribution == 'OracleLinux' and ansible_distribution_major_version == "7"

- name: YUM | Remove previous docker
  yum: name=docker state=absent

- block:
    - name: YUM | Configure Docker repository
      yum_repository:
        name: dockerrepo
        description: Docker Repository
        baseurl: "https://yum.dockerproject.org/repo/main/{{ docker_package_directory }}/{{ ansible_distribution_major_version }}/"
        enabled: 1
        gpgcheck: 1
        gpgkey: https://yum.dockerproject.org/gpg
    - name: YUM | Remove previous docker-io
      yum: name=docker-io state=absent
    - name: YUM | Install Docker Application
      yum: name=docker-engine state=present
  when: ansible_distribution_version != "6.5"

- name: YUM | Install RHEL/OEL 6.5 Supported Docker
  yum: name="{{ item }}" state=present
  with_items:
    - device-mapper-libs-1.02.117-7.el6_8.1.x86_64
    - docker-io
  when: ansible_distribution_version == "6.5"
