---
#For Ubuntu Trusty, Wily, and Xenial, it’s recommended to install the linux-image-extra kernel package.
#The linux-image-extra package allows you use the aufs storage driver.
- name: Docker | CE | Ubuntu | Install the linux-image-extra kernal package
  apt: name="linux-image-extra-{{ ansible_kernel }}" state=present
  when: ansible_distribution_version in ['14.04','15.10']

#If you are installing on Ubuntu 14.04, apparmor is required.
- name: Docker | CE | Ubuntu | Install AppArmor Dependency
  apt: name=apparmor state=present
  when: ansible_distribution_version in "14.04"

- block:
    - name: Docker | CE | APT | Add Docker GPG Key
      apt_key:
        id: "{{ docker_apt_key_id }}"
        url: "{{ docker_apt_key_url }}"
        state: present
  rescue:
    - name: Docker | CE | APT | Add Docker GPG Key | Rescue
      shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
      register: docker_pip_exists
      failed_when: false
      changed_when: false
    - name: Docker | CE | APT | Get Docker GPG Key
      uri:
        url: https://download.docker.com/linux/ubuntu/gpg
      register: docker_apt_key
    - debug: var=docker_apt_key
    - name: Docker | CE | APT | Add Docker GPG Key
      apt_key:
        id: "{{ docker_apt_key_id }}"
        url: "{{ docker_apt_key_url }}"
        state: present


#Docker’s APT repository contains Docker 1.7.1 and higher.
- name: Docker | CE | APT | Configure Docker repository
  apt_repository:
    repo: "{{ docker_apt_repo_url }}"
    state: present

- name: Docker | CE | APT | Enable Edge repository
  apt_repository:
    repo: "{{ docker_apt_repo_url_edge }}"
    state: present
  when: docker_channel == "edge"
  notify: Docker | CE | YUM | Upgrade to Edge
