---
- name: Docker | CE | YUM | Install yum-utils
  yum: name=yum-utils

- name: Docker | CE | YUM | Deploy repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Docker | CE | YUM | Enable edge repository
  yum_repository:
    name: docker-ce-edge
    description: "Docker CE Edge - $basearch"
    baseurl: "https://download.docker.com/linux/centos/7/$basearch/edge"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
    enabled: yes
    file: docker-ce
  when: docker_channel == "edge"
  notify: Docker | CE | YUM | Upgrade to Edge

- name: Docker | CE | YUM | Oracle Linux
  include: os/oracle.yml
  when: ansible_distribution == 'OracleLinux'

- name: Docker | CE | YUM | Remove older Docker installations
  yum: name={{ item }} state=absent
  with_items:
    - docker
    - docker-common
    - docker-selinux
    - container-selinux
    - docker-engine-selinux
    - docker-engine

- name: YUM | Install Docker Application
  yum: name=docker-ce state=present
  notify: Docker | Restart Docker
